export const WILAYAH_KEDIRI = {
  "Badas": [
    "Badas",
    "Blaru",
    "Bringin",
    "Canggu",
    "Lamong",
    "Sekoto"
  ],
  "Banyakan": [
    "Banyakan",
    "Jabon",
    "Jatirejo",
    "Manyaran",
    "Maron",
    "Ngablak",
    "Parang",
    "Sendang",
    "Tiron"
  ],
  "Gampengrejo": [
    "Gampeng",
    "Jongbiru",
    "Kalibelo",
    "Kepuhrejo",
    "Ngebrak",
    "Plosorejo",
    "Putih",
    "Sambirejo",
    "Sambiresik",
    "Wanengpaten"
  ],
  "Grogol": [
    "Bakalan",
    "Datengan",
    "Gambyok",
    "Grogol",
    "Kalipang",
    "Sonorejo",
    "Sumberjo",
    "Wonoasri"
  ],
  "Gurah": [
    "Adan-Adan",
    "Bangkok",
    "Banyuanyar",
    "Blimbing",
    "Bogem",
    "Gabru",
    "Gayam",
    "Gempolan",
    "Gurah",
    "Kranggan",
    "Ngasem",
    "Nglumbang",
    "Sukorejo",
    "Sumbercangkring",
    "Tambakrejo",
    "Tiru Kidul",
    "Tiru Lor",
    "Wonojoyo"
  ],
  "Kandangan": [
    "Banaran",
    "Jerukwangi",
    "Jlumbang",
    "Kandangan",
    "Karangtengah",
    "Kasreman",
    "Kemiri",
    "Klampisan",
    "Medowo",
    "Mlancu"
  ],
  "Kandat": [
    "Blabak",
    "Cendono",
    "Kandat",
    "Karangrejo",
    "Ngletih",
    "Ngreco",
    "Purworejo",
    "Ringinsari",
    "Selosari",
    "Sumberjo",
    "Tegalan"
  ],
  "Kayen Kidul": [
    "Bangsongan",
    "Baye",
    "Jambu",
    "Kayen Kidul",
    "Nanggungan",
    "Padangan",
    "Sambirobyong",
    "Sekaran",
    "Semambung",
    "Sukoharjo"
  ],
  "Kepung": [
    "Besowo",
    "Damarwulan",
    "Kampungbaru",
    "Kebonrejo",
    "Keling",
    "Kencong",
    "Siman"
  ],
  "Kras": [
    "Banjaranyar",
    "Bendosari",
    "Jabang",
    "Jambean",
    "Kanigoro",
    "Karangtalun",
    "Krandang",
    "Kras",
    "Mojosari",
    "Nyawangan",
    "Pelas",
    "Purwodadi",
    "Rejomulyo",
    "Setonorejo"
  ],
  "Kunjang": [
    "Balongjeruk",
    "Kapas",
    "Kapi",
    "Kunjang",
    "Kuwik",
    "Pakis",
    "Parelor",
    "Tenggerlor",
    "Wonorejo"
  ],
  "Mojo": [
    "Blimbing",
    "Jugo",
    "Kedawung",
    "Keniten",
    "Kranding",
    "Kraton",
    "Maesan",
    "Mlati",
    "Mojo",
    "Mondo",
    "Ngadi",
    "Pamongan",
    "Petok",
    "Petungroto",
    "Ploso",
    "Ponggok",
    "Sukoanyar",
    "Surat",
    "Tambibendo"
  ],
  "Ngadiluwih": [
    "Badal",
    "Badal Pandean",
    "Banggle",
    "Banjarejo",
    "Branggahan",
    "Mangunrejo",
    "Ngadiluwih",
    "Purwokerto",
    "Rembang",
    "Rembangkepuh",
    "Seketi",
    "Tales",
    "Wonorejo"
  ],
  "Ngancar": [
    "Babadan",
    "Bedali",
    "Jagul",
    "Kunjang",
    "Manggis",
    "Margourip",
    "Ngancar",
    "Pandantoyo",
    "Sugihwaras"
  ],
  "Ngasem": [
    "Doko",
    "Gogorante",
    "Karangrejo",
    "Kwadungan",
    "Nambaan",
    "Ngasem",
    "Paron",
    "Sukorejo",
    "Sumberejo",
    "Toyoresmi",
    "Tugurejo",
    "Wonocatur"
  ],
  "Pagu": [
    "Bendo",
    "Bulupasar",
    "Jagung",
    "Kambingan",
    "Menang",
    "Pagu",
    "Semanding",
    "Sitimert0",
    "Tanjung",
    "Tengger Kidul",
    "Wates",
    "Wonosari"
  ],
  "Papar": [
    "Dawuhan Kidul",
    "Jambangan",
    "Janti",
    "Kedungmalang",
    "Kwaron",
    "Maduretno",
    "Minggiran",
    "Ngampel",
    "Papar",
    "Pehkulon",
    "Pehwetan",
    "Puhjajar",
    "Purwotengah",
    "Srikaton",
    "Sukomoro",
    "Tanon"
  ],
  "Pare": [
    "Bendo",
    "Darungan",
    "Gedangsewu",
    "Pare",
    "Sambirejo",
    "Sidorejo",
    "Sumberbendo",
    "Tulungrejo"
  ],
  "Plemahan": [
    "Banjarejo",
    "Bogokidul",
    "Kayen Lor",
    "Langenharjo",
    "Mejono",
    "Mojoayu",
    "Mojokerep",
    "Ngino",
    "Payaman",
    "Plemahan",
    "Puhjarak",
    "Ringinpitu",
    "Sidowarek",
    "Sukoharjo",
    "Tegowangi",
    "Wonokerto"
  ],
  "Plosoklaten": [
    "Brenggolo",
    "Donganti",
    "Gondang",
    "Jarak",
    "Kawedusan",
    "Kayunan",
    "Klanderan",
    "Panjer",
    "Plosokidul",
    "Plosolor",
    "Pranggang",
    "Sepawon",
    "Sumberagung",
    "Wonorejo Trisulo"
  ],
  "Puncu": [
    "Asmorobangun",
    "Gadungan",
    "Manggis",
    "Satak",
    "Sidomulyo",
    "Watugede",
    "Wonorejo"
  ],
  "Purwoasri": [
    "Belor",
    "Blawe",
    "Dawuhan",
    "Dayu",
    "Jantok",
    "Karangpakis",
    "Ketawang",
    "Klampitan",
    "Mekikis",
    "Merjoyo",
    "Mranggen",
    "Pandansari",
    "Pesing",
    "Purwoasri",
    "Purwodadi",
    "Sidomulyo",
    "Sumberjo",
    "Wonotengah",
    "Woromarto"
  ],
  "Ringinrejo": [
    "Batuaji",
    "Dawung",
    "Jemekan",
    "Nambakan",
    "Purwodadi",
    "Ringinrejo",
    "Sambi",
    "Selodono",
    "Srikaton",
    "Susuhbango"
  ],
  "Semen": [
    "Bobang",
    "Joho",
    "Kanyoran",
    "Kedak",
    "Pagung",
    "Puhsarang",
    "Selopanggung",
    "Sidomulyo",
    "Titik"
  ],
  "Tarokan": [
    "Blimbing",
    "Bulusari",
    "Cengkok",
    "Jati",
    "Kaliboto",
    "Kalirong",
    "Kedungsari",
    "Tarokan"
  ],
  "Wates": [
    "Gadungan",
    "Jajar",
    "Janti",
    "Joho",
    "Karanganyar",
    "Pagu",
    "Plaosan",
    "Pojok",
    "Segaran",
    "Sidomulyo",
    "Silir",
    "Sumberagung",
    "Tawang",
    "Tempurejo",
    "Wates",
    "Wonorejo"
  ]
};
